name: Déploiement automatique IONOS

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Transférer les fichiers modifiés via SFTP
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code Git
        uses: actions/checkout@v4

      - name: Synchroniser les fichiers via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          local_path: './*'
          remote_path: './cv-web/'
          sftp_only: true
          rsyncArgs: '--exclude=*.scss --exclude=*.map --exclude=README.md --exclude=.gitignore --exclude=.git* --exclude=.github'