name: Déploiement automatique IONOS

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: Transférer les fichiers via rsync
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code Git
        uses: actions/checkout@v4

      - name: Synchroniser les fichiers avec rsync
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.FTP_PASSWORD }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no -p 22" \
            --exclude='*.scss' \
            --exclude='*.map' \
            --exclude='README.md' \
            --exclude='.gitignore' \
            --exclude='.git*' \
            --exclude='.github' \
            ./ ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }}:./cv-web/